version: '3.8'

services:
  auth:
    build: .
    deploy:
      replicas: 3
    networks:
      - nginx_mylocal
  nginx:
    image: nginx:1.16.0-alpine
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
    - nginx_mylocal
networks:
  nginx_mylocal:
    external: true
