version: '3.8'

services:
  user:
    build: .
    deploy:
      replicas: 3
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
    networks:
      - nginx_mylocal
      - mylocal
    depends_on:
      - dbuser
  dbuser:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
#    volumes:
#      - ./.database/postgres/data:/var/lib/postgresql/data
    networks:
      - mylocal
  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx_mylocal
networks:
  mylocal:
    driver: bridge
  nginx_mylocal:
    external: true
